name: CI/CD for Flask App

on:
  push:
    branches:
      - tbat

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t anhtuan284/clinic-flask .

    - name: Push Docker image to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push anhtuan284/clinic-flask

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create .env file
      run: |
          echo "SQLALCHEMY_DATABASE_URI=${{ secrets.SQLALCHEMY_DATABASE_URI }}" > .env
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
          echo "CLOUDINARY_CLOUD_NAME=${{ env.CLOUDINARY_CLOUD_NAME }}" >> .env
          echo "CLOUDINARY_API_KEY=${{ env.CLOUDINARY_API_KEY }}" >> .env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env
          echo "VNPAY_RETURN_URL=${{ env.VNPAY_RETURN_URL }}" >> .env
          echo "VNPAY_PAYMENT_URL=${{ env.VNPAY_PAYMENT_URL }}" >> .env
          echo "VNPAY_API_URL=${{ env.VNPAY_API_URL }}" >> .env
          echo "VNPAY_TMN_CODE=${{ secrets.VNPAY_TMN_CODE }}" >> .env
          echo "VNPAY_HASH_SECRET_KEY=${{ secrets.VNPAY_HASH_SECRET_KEY }}" >> .env
          echo "MOMO_ENDPOINT=${{ env.MOMO_ENDPOINT }}" >> .env
          echo "MOMO_ACCESS_KEY=${{ secrets.MOMO_ACCESS_KEY }}" >> .env
          echo "MOMO_SECRET_KEY=${{ secrets.MOMO_SECRET_KEY }}" >> .env
          echo "MOMO_REDIRECT_URL=${{ env.MOMO_REDIRECT_URL }}" >> .env
          echo "MOMO_IPN_URL=${{ env.MOMO_IPN_URL }}" >> .env

    - name: Copy .env file into clinicapp directory
      run: cp .env clinicapp/

    - name: Deploy to production
      run: |
        docker pull anhtuan284/clinic-flask
        docker run -d \
          -v "$(pwd)/.env:/app/clinicapp/.env" \
          -p 5000:5000 anhtuan284/clinic-flask
    

    - name: Trigger Deploy on Render
      run: curl ${{ secrets.RENDER_DEPLOY_HOOK}}

    - name: Debug
      run: echo ${{ secrets.SQLALCHEMY_DATABASE_URI }}
