name: CI/CD for Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t anhtuan284/clinic-flask .

    - name: Push Docker image to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push anhtuan284/clinic-flask

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to production
      run: |
        docker pull anhtuan284/clinic-flask
        docker run -d -p 5000:5000 anhtuan284/clinic-flask

    - name: Trigger Deploy on Render
      run: curl ${{ secrets.RENDER_DEPLOY_HOOK}}
